language: perl
sudo: false

install:

  - cpanm -n -l /tmp/myftpd URI AnyEvent AnyEvent::FTP::Server Proc::Daemon
  - perl -I/tmp/myftpd/lib/perl5/ t/bin/ftpd -d
  
  - cpanm -n -l /tmp/myhttpd Mojolicious Mojolicious::Plugin::Directory Proc::Daemon
  - perl -I/tmp/myhttpd/lib/perl5/ t/bin/httpd -d 

  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - dzil run 'maint/travis-run-test'
