language: perl
sudo: false

install:
  - perlbrew list
  - ./maint/travis-dzil nop
  - ./maint/travis-install-deps

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - ./maint/travis-run-test
  - perl maint/ci-test-plugins.pl

cache:
  directories:
    - $HOME/mylib

env:
  global:
    - PERL_USE_UNSAFE_INC=0
  matrix:
    - INSTALL_OPTIONAL="Test2::Harness File::Listing File::Listing::Ftpcopy HTML::LinkExtor HTTP::Tiny LWP PkgConfig PkgConfig::LibPkgConf Sort::Versions URI YAML Env::ShellWords Archive::Tar Archive::Zip Devel::Hide Readonly Alien::Base::ModuleBuild FFI::Platypus Alien::cmake3"
    - INSTALL_OPTIONAL=""

